# Generated by Django 5.1.2 on 2024-10-26 05:46

import django.core.validators
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+09123456789'. Up to 11 digits allowed.", regex='^\\+?1?\\d{9,11}$')], verbose_name='phone number')),
                ('full_name', models.CharField(help_text='این فیلد باید به فارسی وارد شود', max_length=50, verbose_name='نام و نام خانوادگی')),
                ('gender', models.CharField(blank=True, choices=[('Man', 'آقا'), ('Woman', 'خانم')], max_length=50, null=True, verbose_name='جنسیت')),
                ('date_of_birth', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='تصویر پروفایل')),
                ('country', models.CharField(blank=True, default='Iran', help_text='این فیلد باید به فارسی وارد شود', max_length=50, null=True, verbose_name='کشور')),
                ('state', models.CharField(blank=True, help_text='این فیلد باید به فارسی وارد شود', max_length=100, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, help_text='این فیلد باید به فارسی وارد شود', max_length=100, null=True, verbose_name='شهر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='ادمین')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پیوستن')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('email_verified', models.BooleanField(default=False, verbose_name='ایمیل تایید شده')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='تلفن تایید شده')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'حساب های کاربری',
            },
        ),
    ]
