# Generated by Django 5.1.2 on 2024-10-15 13:05

import django.core.validators
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number')),
                ('first_name', models.CharField(help_text='این فیلد باید به فارسی وارد شود', max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(help_text='این فیلد باید به فارسی وارد شود', max_length=50, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(blank=True, help_text='این فیلد باید به فارسی وارد شود', max_length=50, null=True, verbose_name='نام پدر')),
                ('gender', models.CharField(blank=True, choices=[('Man', 'آقا'), ('Woman', 'خانم')], max_length=50, null=True, verbose_name='جنسیت')),
                ('date_of_birth', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('nationality_id', models.CharField(max_length=10, verbose_name='شماره ملی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل')),
                ('home_phone', models.CharField(blank=True, help_text='با پیش شماره (مثال 02155667788)', max_length=11, null=True, verbose_name='شماره منزل')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='بایوگرافی')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='تصویر پروفایل')),
                ('country', models.CharField(blank=True, default='Iran', help_text='این فیلد باید به فارسی وارد شود', max_length=50, null=True, verbose_name='کشور')),
                ('state', models.CharField(blank=True, help_text='این فیلد باید به فارسی وارد شود', max_length=100, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, help_text='این فیلد باید به فارسی وارد شود', max_length=100, null=True, verbose_name='شهر')),
                ('address', models.TextField(blank=True, help_text='این فیلد باید به فارسی وارد شود', max_length=500, null=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='ادمین')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پیوستن')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('email_verified', models.BooleanField(default=False, verbose_name='ایمیل تایید شده')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='تلفن تایید شده')),
                ('password_reset_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='توکن بازنشانی رمز عبور')),
                ('password_reset_expiry', models.DateTimeField(blank=True, null=True, verbose_name='انقضای توکن')),
                ('receive_marketing_emails', models.BooleanField(default=False, verbose_name='دریافت ایمیل های تبلیغاتی')),
                ('receive_sms_notifications', models.BooleanField(default=False, verbose_name='دریافت اعلان های پیامکی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
