# Generated by Django 5.1.2 on 2024-10-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=models.CharField(blank=True, default='ایران', help_text='این فیلد باید به فارسی وارد شود', max_length=50, null=True, verbose_name='کشور'),
        ),
    ]
