# Generated by Django 5.0.2 on 2024-10-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name_plural': 'حساب های کاربری'},
        ),
    ]
