# Generated by Django 5.1.2 on 2024-10-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_alter_myuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='جنسیت'),
        ),
    ]
