# Generated by Django 5.1.2 on 2024-11-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenfitText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_1', models.CharField(max_length=16, verbose_name='موضوع ۱')),
                ('info_1', models.TextField(verbose_name='اطلاعات ۱')),
                ('topic_2', models.CharField(max_length=16, verbose_name='موضوع ۲')),
                ('info_2', models.TextField(verbose_name='اطلاعات ۲')),
                ('topic_3', models.CharField(max_length=16, verbose_name='موضوع ۳')),
                ('info_3', models.TextField(verbose_name='اطلاعات ۳')),
            ],
            options={
                'verbose_name': 'متن فایده\u200cها',
                'verbose_name_plural': 'متن\u200cهای فایده\u200cها',
            },
        ),
        migrations.CreateModel(
            name='FirstPageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_title_1', models.CharField(max_length=55, verbose_name='عنوان بزرگ ۱')),
                ('small_title_1', models.CharField(max_length=55, verbose_name='عنوان کوچک ۱')),
                ('big_title_2', models.CharField(max_length=55, verbose_name='عنوان بزرگ ۲')),
                ('small_title_2', models.CharField(max_length=55, verbose_name='عنوان کوچک ۲')),
                ('big_title_3', models.CharField(max_length=55, verbose_name='عنوان بزرگ ۳')),
                ('small_title_3', models.CharField(max_length=55, verbose_name='عنوان کوچک ۳')),
            ],
            options={
                'verbose_name': 'متن صفحه اول',
                'verbose_name_plural': 'متن\u200cهای صفحه اول',
            },
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font', models.CharField(choices=[('فونت پرستو', 'فونت پرستو'), ('فونت ساحل', 'فونت ساحل'), ('فونت صمیم', 'فونت صمیم'), ('(پیشنهاد) فونت تنها', '(پیشنهاد) فونت تنها'), ('فونت وزیر', 'فونت وزیر'), ('فونت یکان', 'فونت یکان')], max_length=50, verbose_name='فونت')),
            ],
            options={
                'verbose_name': 'فونت',
                'verbose_name_plural': 'فونت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='GuideInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_pic', models.ImageField(upload_to='web_pics', verbose_name='تصویر چپ')),
                ('left_title', models.CharField(max_length=55, verbose_name='عنوان چپ')),
                ('left_text', models.TextField(verbose_name='متن چپ')),
                ('right_pic', models.ImageField(upload_to='web_pics', verbose_name='تصویر راست')),
                ('right_title', models.CharField(max_length=55, verbose_name='عنوان راست')),
                ('right_text', models.TextField(verbose_name='متن راست')),
            ],
            options={
                'verbose_name': 'اطلاعات راهنما',
                'verbose_name_plural': 'اطلاعات راهنما',
            },
        ),
        migrations.CreateModel(
            name='GuideText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_text', models.TextField(verbose_name='متن راهنما')),
            ],
            options={
                'verbose_name': 'متن راهنما',
                'verbose_name_plural': 'متن\u200cهای راهنما',
            },
        ),
        migrations.CreateModel(
            name='LearningEnglishText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_big_title', models.CharField(max_length=55, verbose_name='عنوان بزرگ چپ')),
                ('left_small_title', models.CharField(max_length=55, verbose_name='عنوان کوچک چپ')),
                ('right_big_title', models.CharField(max_length=55, verbose_name='عنوان بزرگ راست')),
                ('right_small_title', models.CharField(max_length=55, verbose_name='عنوان کوچک راست')),
            ],
            options={
                'verbose_name': 'متن یادگیری انگلیسی',
                'verbose_name_plural': 'متن\u200cهای یادگیری انگلیسی',
            },
        ),
    ]
