# Generated by Django 5.1.2 on 2024-11-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Text_App', '0003_alter_benfittext_info_1_alter_benfittext_info_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benfittext',
            options={'verbose_name_plural': 'متن\u200cهای مزیت ها (صفحه اصلی)'},
        ),
        migrations.AlterModelOptions(
            name='guideinfo',
            options={'verbose_name_plural': 'راهنما با شکل (صفحه راهنما)'},
        ),
        migrations.AlterModelOptions(
            name='learningenglishtext',
            options={'verbose_name_plural': 'متن\u200cهای بخش یادگیری انگلیسی (صفحه اصلی)'},
        ),
    ]
