# Generated by Django 5.1.2 on 2024-11-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Text_App', '0004_alter_benfittext_options_alter_guideinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideinfo',
            name='main_topic',
            field=models.CharField(default='none', max_length=55, verbose_name='موضوع'),
        ),
    ]
