# Generated by Django 5.1.2 on 2024-11-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Text_App', '0005_guideinfo_main_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideinfo',
            name='main_topic',
            field=models.CharField(max_length=55, verbose_name='موضوع'),
        ),
    ]
