# Generated by Django 5.1.2 on 2024-11-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Text_App', '0007_remove_guideinfo_main_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benfittext',
            name='main_topic_color',
        ),
    ]
