# Generated by Django 5.1.2 on 2024-11-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Text_App', '0008_remove_benfittext_main_topic_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidetext',
            name='main_topic_color',
        ),
        migrations.AddField(
            model_name='benfittext',
            name='main_topic_color',
            field=models.CharField(choices=[('black', 'مشکی'), ('#7335b7', 'بنفش')], default='#7335b7', max_length=55, verbose_name='رنگ تایتل موضوع'),
        ),
    ]
