# Generated by Django 5.1.2 on 2024-11-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Text_App', '0009_remove_guidetext_main_topic_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='font',
            field=models.CharField(choices=[('parastoo', 'فونت پرستو'), ('sahel', 'فونت ساحل'), ('samim', 'فونت صمیم'), ('tanha', '(پیشنهاد) فونت تنها'), ('vazir', 'فونت وزیر'), ('yekan', 'فونت یکان')], max_length=50, verbose_name='فونت'),
        ),
    ]
