# Generated by Django 5.1.2 on 2024-11-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Text_App', '0010_alter_font_font'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Font',
        ),
    ]
