# Generated by Django 5.1.2 on 2024-11-03 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Play_App', '0002_remove_userflashcardprogress_flashcard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='box',
        ),
        migrations.AddField(
            model_name='word',
            name='current_box',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='word',
            name='back_word',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='word',
            name='current_day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='word',
            name='front_word',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='word',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Play_App.word')),
            ],
        ),
    ]
