# Generated by Django 5.1.2 on 2024-11-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Play_App', '0003_remove_word_box_word_current_box_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReviewLog',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
