# Generated by Django 5.1.2 on 2024-11-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Play_App', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='box',
            field=models.IntegerField(default=1, verbose_name='جعبه'),
        ),
        migrations.AddField(
            model_name='word',
            name='day',
            field=models.IntegerField(default=1, verbose_name='روز'),
        ),
        migrations.AddField(
            model_name='word',
            name='last_reviewed',
            field=models.DateField(auto_now=True, verbose_name='تاریخ آخرین بازی'),
        ),
        migrations.AddField(
            model_name='word',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغیر'),
        ),
    ]
