# Generated by Django 5.1.2 on 2024-11-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Play_App', '0006_word_box_word_day_word_last_reviewed_word_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='back_word',
            field=models.CharField(max_length=255, verbose_name='کلمه پشت'),
        ),
        migrations.AlterField(
            model_name='word',
            name='front_word',
            field=models.CharField(max_length=255, verbose_name='کلمه رو'),
        ),
    ]
