# Generated by Django 5.1.2 on 2024-11-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Play_App', '0007_alter_word_back_word_alter_word_front_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='تصحیح'),
        ),
    ]
