# Generated by Django 5.1.2 on 2024-11-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Play_App', '0009_word_lock_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='last_reviewed',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بازی'),
        ),
    ]
