# Generated by Django 5.1.2 on 2024-11-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Play_App', '0011_remove_word_lock_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='lock_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان قفل شدن بازی'),
        ),
    ]
